"""
rag — "Ask the Bot": a fully local, offline RAG pipeline over a portfolio's
own Reasoning Log / Trade History, generated by a small LLM running
on-device via Apple's MLX framework. No API calls, no cloud, no keys.

MLX only runs on Apple Silicon, so availability is detected ONCE here at
import time — never at request time. On any other platform (the Fly.io
deployment, an Intel Mac) the rest of the app runs untouched and the
feature reports itself unavailable; nothing in this package may assume the
imports below succeeded.
"""

from __future__ import annotations

MLX_AVAILABLE = False
UNAVAILABLE_REASON = ""

try:
    import mlx_lm  # noqa: F401 — probe only; the real use lives in llm.py
    import sentence_transformers  # noqa: F401 — probe only; used by embed.py
    MLX_AVAILABLE = True
except Exception as exc:  # ImportError on non-Apple hardware / missing deps
    UNAVAILABLE_REASON = str(exc)
